# Generated by Django 4.0.3 on 2022-06-12 16:17

import api.models
from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('openHours', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliveryType', models.CharField(max_length=200)),
                ('products', jsonfield.fields.JSONField(null=True)),
                ('inpostDetails', jsonfield.fields.JSONField(null=True)),
                ('totalCost', models.FloatField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to=api.models.upload_path)),
                ('count', models.IntegerField(default=20)),
                ('categories', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=9)),
            ],
        ),
    ]
