# Generated by Django 4.0.3 on 2022-04-16 10:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=api.models.upload_path),
        ),
    ]
