# Generated by Django 4.0.3 on 2022-06-09 22:35

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deliveryType', models.CharField(max_length=200)),
                ('products', jsonfield.fields.JSONField(null=True)),
                ('inpostDetails', jsonfield.fields.JSONField(null=True)),
                ('totalCost', models.FloatField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=500)),
                ('status', models.CharField(default='New', max_length=25)),
            ],
        ),
    ]
