# Generated by Django 4.0.3 on 2022-05-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_product_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
